### ISSUE TITLE
Error when run tronbox migrate

### ISSUE THREAD

**Issue by khanhnd69** [Tronbox-boxes/metacoin-box#1]
`**~/workspace/metacoin-box (master) $ tronbox migrate**`
```
Using network 'development'.

Error: Could not find built Migrations contract: Cannot read property 'fullNode' of undefined
    at Object.lastCompletedMigration (/home/ubuntu/.nvm/versions/node/v9.11.2/lib/node_modules/tronbox/build/webpack:/packages/truffle-migrate/index.js:251:1)
    at Object.needsMigrating (/home/ubuntu/.nvm/versions/node/v9.11.2/lib/node_modules/tronbox/build/webpack:/packages/truffle-migrate/index.js:278:1)
    at runMigrations (/home/ubuntu/.nvm/versions/node/v9.11.2/lib/node_modules/tronbox/build/webpack:/packages/truffle-core/lib/commands/migrate.js:75:1)
    at /home/ubuntu/.nvm/versions/node/v9.11.2/lib/node_modules/tronbox/build/webpack:/packages/truffle-core/lib/commands/migrate.js:104:1
    at detectFromAddress (/home/ubuntu/.nvm/versions/node/v9.11.2/lib/node_modules/tronbox/build/webpack:/packages/truffle-core/lib/environment.js:55:1)
    at /home/ubuntu/.nvm/versions/node/v9.11.2/lib/node_modules/tronbox/build/webpack:/packages/truffle-core/lib/environment.js:62:1
    at detectNetworkId (/home/ubuntu/.nvm/versions/node/v9.11.2/lib/node_modules/tronbox/build/webpack:/packages/truffle-core/lib/environment.js:50:1)
    at Object.detect (/home/ubuntu/.nvm/versions/node/v9.11.2/lib/node_modules/tronbox/build/webpack:/packages/truffle-core/lib/environment.js:60:1)
    at /home/ubuntu/.nvm/versions/node/v9.11.2/lib/node_modules/tronbox/build/webpack:/packages/truffle-core/lib/commands/migrate.js:89:1
    at finished (/home/ubuntu/.nvm/versions/node/v9.11.2/lib/node_modules/tronbox/build/webpack:/~/truffle-workflow-compile/index.js:53:1)
    at /home/ubuntu/.nvm/versions/node/v9.11.2/lib/node_modules/tronbox/build/webpack:/packages/truffle-compile/index.js:314:1
    at /home/ubuntu/.nvm/versions/node/v9.11.2/lib/node_modules/tronbox/build/webpack:/packages/truffle-compile/profiler.js:158:1
    at /home/ubuntu/.nvm/versions/node/v9.11.2/lib/node_modules/tronbox/build/webpack:/~/async/dist/async.js:3888:1
    at /home/ubuntu/.nvm/versions/node/v9.11.2/lib/node_modules/tronbox/build/webpack:/~/async/dist/async.js:473:1
    at replenish (/home/ubuntu/.nvm/versions/node/v9.11.2/lib/node_modules/tronbox/build/webpack:/~/async/dist/async.js:1006:1)
    at iterateeCallback (/home/ubuntu/.nvm/versions/node/v9.11.2/lib/node_modules/tronbox/build/webpack:/~/async/dist/async.js:995:1)
    at /home/ubuntu/.nvm/versions/node/v9.11.2/lib/node_modules/tronbox/build/webpack:/~/async/dist/async.js:969:1
    at /home/ubuntu/.nvm/versions/node/v9.11.2/lib/node_modules/tronbox/build/webpack:/~/async/dist/async.js:3885:1
    at /home/ubuntu/.nvm/versions/node/v9.11.2/lib/node_modules/tronbox/build/webpack:/packages/truffle-compile/profiler.js:154:1
    at /home/ubuntu/.nvm/versions/node/v9.11.2/lib/node_modules/tronbox/build/webpack:/~/async/dist/async.js:1140:1
    at /home/ubuntu/.nvm/versions/node/v9.11.2/lib/node_modules/tronbox/build/webpack:/~/async/dist/async.js:473:1
    at iteratorCallback (/home/ubuntu/.nvm/versions/node/v9.11.2/lib/node_modules/tronbox/build/webpack:/~/async/dist/async.js:1064:1)
    at /home/ubuntu/.nvm/versions/node/v9.11.2/lib/node_modules/tronbox/build/webpack:/~/async/dist/async.js:969:1
    at /home/ubuntu/.nvm/versions/node/v9.11.2/lib/node_modules/tronbox/build/webpack:/~/async/dist/async.js:1137:1
    at /home/ubuntu/.nvm/versions/node/v9.11.2/lib/node_modules/tronbox/build/webpack:/packages/truffle-compile/profiler.js:133:1
    at FSReqWrap.oncomplete (fs.js:171:5)
```

**Comment by sullof** [comment]
That was caused by a bug in TronBox 2.0.0 which affected the first migration. Install the new version with
``` 
Npm i -g tronbox@latest
```
Alternatively, force the migration calling
```
tronbox migrate —reset
```

**Comment by sullof** [comment]
I just noticed that tronbox v2.0.1 has been published yet. But, if you run 
```
bash scripts/migrate.sh
```
you solve the issue and set the web app.
