### ISSUE TITLE
tronbox compile报错

### ISSUE THREAD

**Issue by lidonghao1116** [Tronbox-boxes/metacoin-box#11]
hello

当我执行tronbox compile 的时候 报错：

(node:51442) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
(node:51442) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:51442) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Error: Error parsing /root/metacoin-box/contracts/ConvertLib.sol: Cannot find module '/root/.tronbox/solc/soljson_v0.5.4.js'
Require stack:
- /usr/local/lib/node_modules/tronbox/build/components/TronSolc.js
- /usr/local/lib/node_modules/tronbox/build/lib/commands/version.js
- /usr/local/lib/node_modules/tronbox/build/lib/commands/index.js
- /usr/local/lib/node_modules/tronbox/build/index.js
- /usr/local/lib/node_modules/tronbox/build/tronbox.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at getWrapper (/usr/local/lib/node_modules/tronbox/build/components/TronSolc.js:1:2350)
    at Object.parseImports (/usr/local/lib/node_modules/tronbox/build/components/Compile/parser.js:1:2359)
    at /usr/local/lib/node_modules/tronbox/build/components/Compile/profiler.js:1:4981
    at /usr/local/lib/node_modules/tronbox/build/components/Resolver/index.js:1:1727
    at /usr/local/lib/node_modules/tronbox/node_modules/async/internal/onlyOnce.js:12:16
    at next (/usr/local/lib/node_modules/tronbox/node_modules/async/whilst.js:68:18)

请帮忙看下这是什么原因呢？多谢

**Comment by lidonghao1116** [comment]
找到问题了
缺少 soljson文件
到https://github.com/ethereum/solc-bin/tree/gh-pages/bin 下载对应版本的即可
